# Usa la imagen base de Odoo 17.0 que mencionas
FROM odoo

# Copia tus módulos personalizados de Odoo al contenedor
COPY ./Odoo/Odoo17/Bintell/addons /mnt/extra-addons


# Define las variables de entorno para la configuración
ENV HOST=db-odoo17-Bintell-prueba
ENV USER=odoo
ENV PASSWORD=odoo

# Aquí puedes agregar cualquier otra configuración que necesites
