services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "C:/Users/Marvin/Documents/Proyecto1/Docker/nginx/Bintell/APP/nginx_config/default.conf:/etc/nginx/conf.d/default.conf"
      - "C:/Users/Marvin/Documents/Proyecto1/Docker/nginx/Bintell/APP/nginx_config/odoo.conf:/etc/nginx/conf.d/odoo.conf"
      - "C:/Users/Marvin/Documents/Proyecto1/Docker/nginx/Bintell/APP/nginx_config/cert.pem:/etc/ssl/cert.pem"
      - "C:/Users/Marvin/Documents/Proyecto1/Docker/nginx/Bintell/APP/nginx_config/private.key:/etc/ssl/private/private.key"


    networks:
      - n8n-network
#    depends_on:
#      - n8n
#      - odoo17-Bintell
#      - odoo17_2-Bintell

networks:
  n8n-network:
    external: true
