name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Se ejecuta cuando se hace push en la rama 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./ # Directorio donde se encuentra el Dockerfile
        file: ./Odoo/Odoo17/Bintell/Dockerfile # Ruta del Dockerfile
        push: true # Esto enviará la imagen a Docker Hub
        tags: marvinordo/odoo17:latest
